### ISSUE TITLE
Download problem in update_local()

### ISSUE THREAD

**Issue by nicolaguidone** [UBESP-DCTV/faers.db#16]
After the download of all .txt file, the function show this error:
Error in download.file(Url, method = method, ...) 
cannot open URL 'https://fis.fda.gov/content/Export/faers_xml_2020q3.zip'.

**Comment by pietrobelloni** [comment]
Since XML data download is causing problems, and the data content of XML and TXT files is the same, we prefer to close issue #18 and focus only on TXT data download.
